# AFTER COMPLETING THIS FILE: RENAME IT AS config.yaml AND SAVE IT IN THE SAME DIRECTORY AS THIS FILE.

huggingface_login:
  email: "YOUR_EMAIL"
  passwd: "YOUR_PASSWORD"

cookies_directory: "./cookies"

collections_directory: "./collections"

data_directory: "./data"

model_directory: "YOUR_MODEL_DIRECTORY"



